{{- range .Values.vaultRoles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  roleName: {{ .data.roleName | quote }}
  policyNames: {{ .data.policyNames | quote }}
  servieAccounts: {{ .data.servieAccounts | quote }}
  servieAccountNameSpaces: {{ .data.servieAccountNameSpaces | quote }}
---
{{- end }}