apiVersion: v1
kind: Service
metadata:
  name: {{ include "kad.fullname" . }}-config-worker
  labels:
    {{- include "kad.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-worker
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: config-worker
