{{- if and .Values.ingressroute.enabled .Values.ingressroute.mtls.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "kad.fullname" . }}-mtls-auth
spec:
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
    - {{ include "kad.fullname" . }}-root-ca
  maxVersion: VersionTLS13
  minVersion: VersionTLS12
  sniStrict: true
{{- end }}
