apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-capten-server
data:
  roleName: vault-role-capten-server
  policyNames: {{ .Values.vaultcred.policyNames | quote }}
  servieAccounts: {{ include "server.serviceAccountName" . }}
  servieAccountNameSpaces: {{ .Release.Namespace }}