openapi: "3.0.3"

info:
  title: SaaS server Open REST API Specification
  description: SaaS server Open REST API specification
  version: 1.0.0

servers:
  - url: /

paths:
  /status:
    get:
      tags:
        - private
      summary: Kubernetes readiness and liveness probe endpoint
      responses:
        '200':
          description: successful operation

  /api-docs:
    get:
      tags:
        - public
      summary: List of APIs provided by the service
      responses:
        '200':
          description: OK

  /climon:
    post:
      tags:
        - public
      summary: deploy the application
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeployRequestPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /deploy:
    post:
      tags:
        - public
      summary: deploy the application
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeployRequestPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /config:
    post:
      tags:
        - public
      summary: deploy the application
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigRequestPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /register/agent:
    post:
      tags:
        - public
      summary: Register agent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '200':
          description: OK
    put:
      tags:
        - public
      summary: Register agent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '200':
          description: OK
    get:
      tags:
        - public
      summary: Register agent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgentRequest'

components:
  schemas:
    AgentRequest:
      title: Agent information
      type: object
      properties:
        customer_id:
          type: string
        endpoint:
          type: string
      required:
        - customer_id
        - endpoint

    Response:
      type: object
      description: Configuration request response
      properties:
        status:
          type: string
        message:
          type: string
      required:
        - status
        - message

    Payload:
      type: object
      properties:
        plugin_name:
          type: string
          description: Plugin name for the operation
        action:
          type: string
          description: Action to be performed
        data:
          type: object
          description: Data for the action
      required:
        - plugin_name
        - action
        - data

    DeployRequestPayload:
      title: Deploy operation request payload
      type: object
      properties:
        operation:
          type: string
        payload:
          allOf:
            - $ref: '#/components/schemas/Payload'
      required:
        - operation
        - payload

    ConfigRequestPayload:
      title: Configure payload
      type: object
      properties:
        operation:
          type: string
        payload:
          allOf:
            - $ref: '#/components/schemas/Payload'
            - properties:
                resource:
                  type: string
                  description: Resource to be configured
              required:
                - resource
      required:
        - operation
        - payload
